### ISSUE TITLE
Avi F5 Config Converter is not converting VirtualService with same IP & Port but different protocol

### ISSUE THREAD

**Issue by senthilkumarvs83** [avinetworks/sdk#24]
While converting the bigip.conf file to the AVI configs it's not recognizing the same IP address with different protocols. The log says "[get_service_obj:592] Skipped: Duplicate IP-Port for vs <<<<<VIP>>>>> "

I need to convert every single VIPs in the .conf file to the AVI configs. Any help would be highly appreciated.

Thanks

**Comment by chaitanyaavi** [comment]
This repo is not maintained its been migrated to https://github.com/vmware/alb-sdk Can you please check with latest release from new repo?
